build and push using actions

diff --git a/.github/workflows/publish-ghcr.yml b/.github/workflows/publish-ghcr.yml
--- a/.github/workflows/publish-ghcr.yml
+++ b/.github/workflows/publish-ghcr.yml
@@ -31,21 +31,42 @@ jobs:
       #   run: |
       #     docker run --rm -i hadolint/hadolint < Dockerfile
 
-      - name: Build Docker image
-        run: |
-          docker build . \
-            --build-arg MARIADB_VERSION=${{ env.MARIADB_VERSION }} \
-            -t ${{ env.DOCKER_IMAGE_FULL }} -f ./Dockerfile .
+      # - name: Build Docker image
+      #   run: |
+      #     docker build . \
+      #       --build-arg MARIADB_VERSION=${{ env.MARIADB_VERSION }} \
+      #       -t ${{ env.DOCKER_IMAGE_FULL }} -f ./Dockerfile .
 
-      # https://github.com/settings/tokens/new?scopes=write:packages
-      - name: Registry login
-        run: |
-          if [ -z "$${{ secrets.GHCR_TOKEN }}" ]; then \
-            echo "Please configure the repository secrets with required variables (GHCR_TOKEN,GHCR_USERNAME)."; \
-            exit 1; \
-          fi; \
-          echo {{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u {{ secrets.GHCR_USERNAME }} --password-stdin
+      # # https://github.com/settings/tokens/new?scopes=write:packages
+      # - name: Registry login
+      #   run: |
+      #     if [ -z "$${{ secrets.GHCR_TOKEN }}" ]; then \
+      #       echo "Please configure the repository secrets with required variables (GHCR_TOKEN,GHCR_USERNAME)."; \
+      #       exit 1; \
+      #     fi; \
+      #     echo {{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u {{ secrets.GHCR_USERNAME }} --password-stdin
 
-      - name: Publish image
-        run: |
-          docker push ${{ env.DOCKER_IMAGE_FULL }}
+      # - name: Publish image
+      #   run: |
+      #     docker push ${{ env.DOCKER_IMAGE_FULL }}
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GHCR_TOKEN }}
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build and push
+        uses: docker/build-push-action@v6
+        with:
+          platforms: linux/amd64
+          push: true
+          tags: |
+            ${{ env.DOCKER_IMAGE_FULL }}
